language:
    java
jdk:
    - oraclejdk8
sudo:
    required
services:
    - docker
before_install:
    - docker run -d --name neo4j -p 7687:7687 -e NEO4J_AUTH=neo4j/neo4j123 -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:3.4-enterprise
    - docker ps -a
install:
    mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    mvn test -P !build-extras -B
cache:
    directories:
        - ~/.m2/repository
after_success:
    - mvn clean test jacoco:report coveralls:report
    - mvn clean test -Pintegration-test
    - .travis/before-deploy.sh
    - .travis/deploy.sh
after_script:
    - docker stop neo4j
    - docker rm -f neo4j
